### ISSUE TITLE
This example does not work with recent versions

### ISSUE THREAD

**Issue by luixal** [primefaces/primevue-nuxtjs-quickstart#7]
This example uses old versions and, when updating PrimeVue to version 2.2.2, it crashes with this error:

```
Could not compile template /home/laperez/dev/primevue-nuxtjs-quickstart/node_modules/@nuxt/vue-app/template/App.js: Cannot resolve "primevue/resources/themes/nova-light/theme.css" from "/home/user/dev/primevue-nuxtjs-quickstart/primevue/resources/themes/nova-light/theme.css"
```

I've updated the following depences, in this order:

* Nuxt: from 2.10.2 to 2.14.6 (still works)
* PrimeVue: **from 1.0.0-beta.14 to 2.2.2** (doesn't work anymore)

So I guess something related to resolving css files has changed between versions. Maybe the theme was taken out of the bundle or something.

Any idea on how to make this work?

**Comment by tugcekucukoglu** [comment]
Please try to run with the latest PrimeVue 2 version.
